# version: "3.9"

services:
  examone:
    image: examone
    container_name: examone
    build:
      context: ..
      dockerfile: ./Deployment/Dockerfile.ExamOne
    ports:
      - "80:8080"
    volumes:
      - /root/docker/volumes/examone/content_root_path/wwwroot:/app/wwwroot
      - /root/docker/volumes/examone/resource:/app/Resource
      - /root/docker/volumes/examone/logs:/app/Logs
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      CONNECTION_STRING: "Server=103.75.185.241;Database=ExamOneDb;User=sa;Password=KNoSyl4rp61kACZ1;TrustServerCertificate=True"

  # mssqlserver:
    # image: mcr.microsoft.com/mssql/server
    # container_name: mssqlserver
    # user: root
    # ports:
      # - "1433:1433"
    # restart: always
    # environment:
      # SA_PASSWORD: "KNoSyl4rp61kACZ1"
      # ACCEPT_EULA: "Y"
      # MSSQL_PID: "Express"
    # volumes:
      # - /root/data/MSSQLSERVER/DATA:/var/opt/mssql/data

# meilisearch:
#   image: getmeili/meilisearch:v1.7
#   container_name: meilisearch
#   ports:
#     - "7700:8080"
#   volumes:
#     - /root/docker/volumes/meili_data:/meili_data
#   environment:
#     MEILI_MASTER_KEY: "d0552b41536279a0ad88bd595327b96f01176a60c2243e906c52ac02375f9bc1"
#   restart: always
#
  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass KNoSyl4rp61kACZ1
